[desc_headers, desc_vals] = describe(expt);
if (~header_written),
    fprintf(fid_meta, '%s\tM\tN\tC\tF\tACC_WITHIN\tACC_WITHIN_STD\tACC_WITHIN_P\tRACC_WITHIN\tRACC_WITHIN_STD\tRACC_WITHIN_P\tKAPPA_WITHIN\tACC_BETWEEN\tACC_BETWEEN_STD\tACC_BETWEEN_P\tRACC_BETWEEN\tRACC_BETWEEN_STD\tRACC_BETWEEN_P\tKAPPA_BETWEEN\tCHI_WITHIN_N\tCHI_ACC_WITHIN\tCHI_BETWEEN_N\tCHI_ACC_BETWEEN\tFISHER_WITHIN\tFISHER_BETWEEN\n', desc_headers);
    header_written = 1;
end
fprintf(fid_meta, '%s\t%d\t%d\t%d\t%s\t%.4f%s\t%d\t%d\t%.4f%s\t%d\t%d\t%.4f\t%.4f%s\t%d\t%d\t%.4f%s\t%d\t%d\t%.4f\t%d\t%.4f%s\t%d\t%.4f%s\t%.4f%s\t%.4f%s\n', ...
        desc_vals, ...
        result.M, result.N, result.C, result.F, ...
        result.within.acc.mean, expt.significance{result.within.acc.H+1}, result.within.acc.std, result.within.acc.P, ...
        result.within.racc.mean, expt.significance{result.within.racc.H+1}, result.within.racc.std, result.within.racc.P, ...
        result.within.kappa.mean, ...
        result.between.acc.mean, expt.significance{result.between.acc.H+1}, result.between.acc.std, result.between.acc.P, ...
        result.between.racc.mean, expt.significance{result.between.racc.H+1}, result.between.racc.std, result.between.racc.P, ...
        result.between.kappa.mean, ...
        result.chi2.within.acc.N, result.chi2.within.acc.values(1) / result.chi2.within.acc.N, expt.significance{result.chi2.within.acc.H+1}, ...
        result.chi2.between.acc.N, result.chi2.between.acc.values(1) / result.chi2.between.acc.N, expt.significance{result.chi2.between.acc.H+1}, ...
        result.fisher.within.P, expt.significance{result.fisher.within.H+1}, result.fisher.between.P, expt.significance{result.fisher.between.H+1});